export const PLUGIN50_GET__READ = "PLUGIN50_GET__READ"
export const PLUGIN50_GET__READ_SUCCEEDED = "PLUGIN50_GET__READ_SUCCEEDED"
export const PLUGIN50_GET__READ_FAILED = "PLUGIN50_GET__READ_FAILED"
export const PLUGIN50_GET_DATA_G1_LIST = "PLUGIN50_GET_DATA_G1_LIST"
export const PLUGIN50_GET_DATA_G1_LIST_SUCCEEDED =
  "PLUGIN50_GET_DATA_G1_LIST_SUCCEEDED"
export const PLUGIN50_GET_DATA_G1_LIST_FAILED =
  "PLUGIN50_GET_DATA_G1_LIST_FAILED"
