export const PLUGIN50_GET__READ = "PLUGIN50_GET__READ"
export const PLUGIN50_GET__READ_SUCCEEDED = "PLUGIN50_GET__READ_SUCCEEDED"
export const PLUGIN50_GET__READ_FAILED = "PLUGIN50_GET__READ_FAILED"
export const PLUGIN50_POST_DATA_G1_CREATE = "PLUGIN50_POST_DATA_G1_CREATE"
export const PLUGIN50_POST_DATA_G1_CREATE_SUCCEEDED =
  "PLUGIN50_POST_DATA_G1_CREATE_SUCCEEDED"
export const PLUGIN50_POST_DATA_G1_CREATE_FAILED =
  "PLUGIN50_POST_DATA_G1_CREATE_FAILED"
